### ISSUE TITLE
Bug: Memory Graph Debugger & Memory Instruments don't work with `swift_binary`

### ISSUE THREAD

**Issue by jpsim** [buildbuddy-io/rules_xcodeproj#1028]
## Describe the bug

Xcode's Memory Graph Debugger and the memory-related instrument profiles such as Leaks and Allocations don't work with `swift_binary` targets with `build_mode = "bazel"`. It works with `build_mode = "xcode"` though.

## Reproduction steps

With f95830d20cbee5fb30ccca95db1574cc10844548:

```console
$ cd examples/simple
$ bazel run xcodeproj && xed .
```

1. Set a breakpoint on the `print("Hello, world!")` line.
2. Build and Run.
3. Click the "Debug Memory Graph" button

![image](https://user-images.githubusercontent.com/474794/188218916-da5d84c1-24cd-42b6-b289-a73e7d5941a7.png)

You should then see this alert:

![image](https://user-images.githubusercontent.com/474794/188218989-993e4282-2ab3-4814-9c75-979b21cf3094.png)

Here are the error messages for searchability:

> Unable to build memory graph
> Unable to acquire required task port (81702:0)

And the full details:

<details>

<summary>Full Details</summary>

```
Details

Unable to acquire required task port (84690:0)
Domain: DTLeaksService
Code: -1
User Info: {
    DVTErrorCreationDateKey = "2022-09-02 18:51:30 +0000";
    DVTRadarComponentKey = 637311;
}
--

Analytics Event: com.apple.dt.memory_graph_capture : {
    "debugSession_coalescedState" = 1;
    "debugSession_isSynthetic" = 0;
    "debugSession_state" = 1;
    "device_model" = "MacBookPro18,4";
    "device_osBuild" = "12.5.1 (21G83)";
    "device_platform" = "com.apple.platform.macosx";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "memgraphDebugger_duration_ms" = 14;
    "memgraphDebugger_precedingCount" = 0;
    "memgraphDebugger_status" = "-1";
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.macosx";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.tool";
    "param_runnable_swiftVersion" = "5.6.1";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "macosx12.3";
    "sdk_osVersion" = "12.3";
    "sdk_variant" = macos;
}
--


System Information

macOS Version 12.5.1 (Build 21G83)
Xcode 13.4 (20503) (Build 13F17a)
Timestamp: 2022-09-02T14:51:30-04:00
```

</details>

## Expected behavior

The Memory Graph Debugger, Leaks Instrument and Allocations Instrument should all work.

They do with Swift CLI's as created by Xcode's New Project wizard.

## Versions
- Bazel: 5.3.0
- rules_xcodeproj: f95830d20cbee5fb30ccca95db1574cc10844548
- rules_apple: 1.1.1
- rules_swift: 1.1.1
- macOS: 12.5.1 (Build 21G83)
- Xcode: 13.4 (20503) (Build 13F17a)

## Additional context

Interestingly SwiftPM-based projects have the same bug, which I've filed with Apple as FB11436273.

**Comment by brentleyjones** [comment]
I'm putting this as a blocker for 1.0 for now, since it's a core Xcode feature.

**Comment by chiragramani** [comment]
I too faced this issue and looks like it's a codesigning issue.

Xcode contacts the leak agent by supplying the PID. The leak agent itself errors out by saying: 

`Process <PID> is not debuggable. Due to security restrictions, leaks cannot show memory contents of restricted processes. ` The leak agent is able to report the leaks but since the above is sent to the STDERR pipe, Xcode shows the above error. (`Unable to acquire the required task port (<PID: 0>)`) further not showing the memory graph.

Since it's a task port-related error, the binary needs to be signed with the entitlements having `com.apple.security.get-task-allow` that will make the process debuggable satisfying the constraints that the leak agent is looking for. I added a post-build step to confirm this and it all works fine. This is the post-build step script contents that we can apply locally to confirm this behavior and the fix:
```
ENTITLEMENTS='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>com.apple.security.get-task-allow</key>
   <true/>
</dict>
</plist>
'
 
echo $ENTITLEMENTS > entitlements.xcent
 
/usr/bin/codesign --force --sign - --entitlements entitlements.xcent --timestamp\=none --generate-entitlement-der $BUILT_PRODUCTS_DIR/$TARGETNAME
```

- I think currently `rules_swift` `swift_binary rule` doesn't take in entitlements. Maybe we can make a change there so that if the entitlements are fed in, it will attempt to codesign as above, with other constraints if needed. 
- Even if the above change goes in, it might not be intuitive for developers to provide these entitlements for swift_binary(relation with the entitlements and linked process debuggability) so maybe we can implicitly post-process it in rules_xcodeproj, given that no entitlements are provided. But if the entitlements are provided explicitly, it will honor what's passed? 

@brentleyjones What are your thoughts here?

**Comment by brentleyjones** [comment]
Interesting. Good find @chiragramani. I'll ponder what's the best path forward with this finding and report back here.

**Comment by jpsim** [comment]
Nice debugging here @chiragramani! Adding that run script phase also worked around the issue for my project.

I've linked back to this thread in the feedback I had filed with Apple (FB11436273) although if we want this to work with shipping versions of Xcode we'd need to find a way to integrate a fix like this into rules_xcodeproj or rules_swift.

**Comment by brentleyjones** [comment]
I would like it if we could add this to rules_swift. We already do some xctest bundling there for apple platforms, it would be nice if it could do this as well. Probably need it behind a feature flag so people can not have the extra codesign step if they don't need it.

Thoughts @keith?

**Comment by BalestraPatrick** [comment]
Do Objective-C target have the same issue at the moment (I haven't tried the memory debugger yet in our project)? If so, we should make sure the fix is applicable to `objc_library`, etc. as well.

**Comment by brentleyjones** [comment]
I was thinking about that last night. I bet all `*_binary` have this issue, so we will have to address this in rules_xcodeproj. I have an idea on how to apply it in Starlark, similar to our Info.plist fixes.
