### ISSUE TITLE
Bug: Address Sanitizer Unavailable in Fresh Project (BwB Mode)

### ISSUE THREAD

**Issue by tinder-cwybranowski** [buildbuddy-io/rules_xcodeproj#1613]
## Describe the bug

The Xcode `Address Sanitizer` feature does not halt on triggering code (nor is a call-stack provided) when accessed via a `rules_xcodeproj`-generated Xcode project in BwB mode.

## Reproduction steps

I've created a [demo repository](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo) that contains the following lanes to compare expected behavior:
- Vanilla Xcode (powered by XcodeGen Xcode project)
- rules_xcodeproj

## Expected behavior

Application execution is halted, and a call-stack identifying the runtime issue is provided.

## Versions
- Bazel: [6.0.0](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo/blob/main/.bazelversion#L1)
- rules_xcodeproj: [0.12.0](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo/blob/main/WORKSPACE#L6)
- rules_apple: 2.0.0 ([transitively via `rules_xcodeproj`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/0.12.0/xcodeproj/repositories.bzl#L90))
- rules_swift: 1.5.1 ([transitively via `rules_xcodeproj`](https://github.com/buildbuddy-io/rules_xcodeproj/blob/0.12.0/xcodeproj/repositories.bzl#L83))

## Additional context

- The `Thread Sanitizer` appears to work as expected, so Runtime Sanitizer support isn't completely unavailable.
- [`Address Sanitizer` works as expected in BwX mode](https://github.com/buildbuddy-io/rules_xcodeproj/issues/1613#issuecomment-1397686073)

**Comment by brentleyjones** [comment]
Does this work in BwX mode?

**Comment by tinder-cwybranowski** [comment]
> Does this work in BwX mode?

Apologies for not specifying BwB mode, I'll update the original post (and the demo repro with that distinction).

I just confirmed it works as expected in BwX mode:

<img width="800" alt="Screen Shot 2023-01-19 at 5 15 36 PM" src="https://user-images.githubusercontent.com/40372184/213574442-5030aced-762a-45c7-9ac6-1bafb6e4429d.png">

**Comment by chiragramani** [comment]
We were discussing about this issue and following are the observations so far:
1. If you add Swift code in your project and enable asan, it works as expected. You can add this code in your project to test this out - https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/examples/sanitizers/AddressSanitizerApp/AddressSanitizerExamples.swift
2. However, I am able to repro the issue for ObjC code. 

I think it might be because of diagnostics not present for ObjC code (ObjCSanitizer.d, ObjCSanitizer.o) in `Objects-normal-asan` but I would wait to get @brentleyjones thoughts on this as well.

**Comment by chiragramani** [comment]
Okay, so I changed the Objc code to take the same example that bazel uses in its test-suite and asan works in ObjC Code as well. You can try this with this code:
```
#import <Foundation/Foundation.h>
#import "ObjcSanitizer.h"

@implementation ObjcSanitizer : NSObject

+ (int)triggerAddressSanitizer {
    volatile int* p;
      {
        volatile int x = 0;
        p = &x;
      }
      return *p;
}

@end

```

![Screenshot 2023-01-19 at 8 21 47 PM](https://user-images.githubusercontent.com/11925399/213616737-ec3b3da8-fa4f-4a02-8566-68b8fc4c959f.png)

Currently not sure, why the original ObjC code doesn't trigger an asan violation in BwB mode whereas the above ObjC code triggers an asan violation.

**Comment by tinder-cwybranowski** [comment]
@chiragramani Thank you very much for taking a look, and validating the original repro case!

---

> If you add Swift code in your project and enable asan, it works as expected. You can add this code in your project to test this out - https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/examples/sanitizers/AddressSanitizerApp/AddressSanitizerExamples.swift

I confirmed that this Swift example correctly triggers Address Sanitizer -- I pushed the change to the [demo repository](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo) as well.

---

> Okay, so I changed the Objc code to take the same example that bazel uses in its test-suite and asan works in ObjC Code as well. You can try this with this code:

I confirmed that this new Objc example correctly triggers Address Sanitizer -- I pushed these changes as well (but kept the original as a failing example).

---

> Currently not sure, why the original ObjC code doesn't trigger an asan violation in BwB mode whereas the above ObjC code triggers an asan violation.

It's definitely strange, but reassuring that it works in some cases -- do we know if the `Heap buffer overflow` vs. `Use of out-of-scope stack memory` distinction is relevant?

**Comment by chiragramani** [comment]
I think something else is happening here. In the repro code, we are making use of `malloc` and `free`. So, when I print out all the symbols of `bazel build //src:ObjcLib --features=asan && nm -a bazel-bin/src/libObjcLib.a`, these symbols are not even there. This might make sense because the code creates a buffer, assigns something, but since its never being used - the compiler in its code-gen must have removed these operations, because of which we don't see asan being applied.(which redzones that asan looks for has no record of this).

Then, instead of returning a hard-coded 1, I updated the code to return the buffer so that this is not stripped off. And I see the symbols in the binary as well as see asan being applied.

```
+ (char *)triggerAddressSanitizer_example1 {
    char *buffer = malloc(80);
    buffer[85] = 'Y';
    free(buffer);
    return buffer;
}
```

![Screenshot 2023-01-22 at 12 52 40 PM](https://user-images.githubusercontent.com/11925399/213939810-5864b20b-bb33-4c69-a350-663ca8fee102.png)

I think we need some ObjC copts here to signal ObjC compilation so that symbols are not removed(no optimization happens).

**Comment by chiragramani** [comment]
Okay, so yes, because of O1 optimization being applied, the symbols are stripped - https://github.com/bazelbuild/bazel/blob/6.0.0/tools/osx/crosstool/cc_toolchain_config.bzl#L2677.

**Comment by brentleyjones** [comment]
We should minimally open an issue against Bazel. This seems surprising?

Regardless, we probably should do something similar to your PR, because as this issue shows, it's not expected to behave the way that it currently does.

**Comment by tinder-cwybranowski** [comment]
> @tinder-cwybranowski can you confirm if https://github.com/buildbuddy-io/rules_xcodeproj/pull/1625 works for your repro?

Thanks for putting up the PR -- [I just confirmed that it now works as expected for my original repro case](https://github.com/tinder-cwybranowski/xcode-runtime-sanitizer-demo/tree/cwybranowski/test-fix/custom_asan_config):

<img width="1911" alt="Screenshot 2023-01-23 at 11 43 13 AM" src="https://user-images.githubusercontent.com/40372184/214098110-c76f95c3-15c3-4d05-b5ea-6c943c546a27.png">
